#! /bin/zsh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color "#FFDFA1"
#bspc config focused_border_color "#FE415A"
bspc config presel_feedback_color "#FFDFA1"


bspc config split_ratio          0.51
bspc config borderless_monocle   false
bspc config gapless_monocle      false

xsetroot -cursor_name left_ptr

## MAGNECIAREAL ##  
lxpolkit &

picom -bf

xss-lock --transfer-sleep-lock -- i3lock-fancy-dualmonitor &

# pgrep -x "glava" > /dev/null || glava -d &
~/.fehbg
~/.config/polybar/launch.sh --magneciareal &
~/.config/magne-scripts/wacom_config.sh DVI-D-0

# pgrep -x thunar > /dev/null || thunar --daemon &
pgrep -x bluetooth-autoconnect > /dev/null || bluetooth-autoconnect --daemon &

kill -9 `pgrep -f "bspc subscribe report node_flag node_focus"`
while read -r line; do

  case "$line" in
    *'locked on')
      bspc config focused_border_color "#FF0000"
      ;;
    *'locked off')
      bspc config focused_border_color "#FFDFA1"
			;;
		*'marked on')
      for mark in `bspc query -N -n .marked`; do
        bspc config -n $mark border_width 5;
      done;
			;;
		*'marked off')
      node=${${line% marked off}##* }
			bspc config -n $node border_width 2
			;;
	esac

  [ ${line%% *} = "node_focus" ] && \
    (bspc config -n ${line##* }.locked focused_border_color "#FF0000" || bspc config focused_border_color "#FFDFA1")

done < <(bspc subscribe report node_flag node_focus)
