#!/bin/sh
NOTIFY_ICON=~/.icons/Fancy-Dark-Icons/apps/48/cantata.svg

if pgrep -x "mpd" > /dev/null; then
  mpd --kill
  notify-send -u low -i $NOTIFY_ICON MPD "mpd killed succesfully"
else
  mpd
  notify-send -u low -i $NOTIFY_ICON MPD "mpd already on"
fi
